name: vitfly
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python版本
  - python=3.8
  
  # 深度学习框架
  - pytorch>=1.12.0
  - torchvision>=0.13.0
  - cpuonly  # CPU版本，如需GPU版本请删除此行
  
  # 数值计算
  - numpy>=1.21.0
  - scipy>=1.7.0
  
  # 图像处理
  - opencv>=4.5.0
  - pillow>=8.3.0
  
  # 数据处理和可视化
  - matplotlib>=3.5.0
  - pandas>=1.3.0
  - pyyaml>=6.0
  - tqdm>=4.62.0
  
  # 开发工具
  - jupyter
  - ipython
  
  # pip安装的包
  - pip
  - pip:
    - airsim>=1.8.1
    
# 可选的GPU版本配置
# 如果有NVIDIA GPU，使用以下配置替换上面的pytorch部分：
# - pytorch>=1.12.0
# - torchvision>=0.13.0
# - pytorch-cuda=11.7  # 或其他CUDA版本