# ViTfly最小实现配置文件
# 适用于Windows AirSim环境

# 模型配置
model:
  input_size: [60, 90]          # 输入图像尺寸 (H, W)
  patch_size: 7                 # 补丁大小
  embed_dim: 64                 # 嵌入维度
  num_layers: 2                 # Transformer层数
  num_heads: 2                  # 注意力头数
  reduction_ratio: 4            # 注意力降维比例
  lstm_hidden: 128              # LSTM隐藏层大小
  dropout: 0.1                  # Dropout比例

# 飞行控制参数
flight:
  desired_velocity: 3.0         # 期望飞行速度 (m/s)
  control_frequency: 10         # 控制频率 (Hz)
  takeoff_altitude: 3.0         # 起飞高度 (m)
  max_flight_duration: 60.0     # 最大飞行时间 (s)
  
# 安全参数
safety:
  max_velocity: 10.0            # 最大速度限制 (m/s)
  max_acceleration: 5.0         # 最大加速度 (m/s²)
  min_height: 0.5               # 最小飞行高度 (m)
  max_height: 50.0              # 最大飞行高度 (m)
  gradual_acceleration: true    # 启用渐进加速
  startup_duration: 3.0         # 渐进加速时间 (s)

# AirSim配置
airsim:
  vehicle_name: "Drone1"        # 无人机名称
  connection_timeout: 30.0      # 连接超时时间 (s)
  camera_name: "front_center"   # 相机名称
  
# 图像处理
image_processing:
  resize_method: "bilinear"     # 调整尺寸方法
  normalization: true           # 启用归一化
  depth_range: [0.0, 1.0]       # 深度值范围

# 日志配置
logging:
  level: "INFO"                 # 日志级别
  performance_log_interval: 50  # 性能日志间隔 (帧数)
  save_flight_data: false      # 保存飞行数据
  
# 训练配置（如果需要训练）
training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 100
  optimizer: "adam"
  loss_function: "mse"
  
# 设备配置
device:
  use_cuda: true                # 使用CUDA（如果可用）
  mixed_precision: false        # 混合精度训练